version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

  deploy-and-launch:
    executor: python/default
    steps:
      - run:
          command: ls

  client-one-job:
    executor: python/default
    steps: 
      - run:
          command: ls 

  client-two-job:
    executor: python/default
    steps:
      - run:
          command: ls 
       

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-and-launch
  second:
    jobs:
      - client-one-job
      - client-two-job
